- name: zookeeper create group
  become: yes
  group:
    name: "{{zookeeper.group}}"

- name: zookeeper create user
  become: yes
  user:
    name: "{{zookeeper.user}}"
    comment: "Zookeeper User"
    system: yes
    group: "{{zookeeper.group}}"

- name: zookeeper myid file
  become: yes
  template:
    src: myid.j2
    dest: "{{zookeeper.config.dataDir}}/myid"
    mode: 0555
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"

- name: zookeeper create config
  become: yes
  template:
    src: zookeeper.properties.j2
    dest: "{{zookeeper.config_file}}"
    mode: 0400
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"

- name: create systemd override file
  become: yes
  file:
    path: "{{zookeeper.systemd_override}}"
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
    state: directory
    mode: 0640

- name: write environment variables
  become: yes
  template:
    src: environment.j2
    dest: "{{zookeeper.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
  notify:
    - reload systemd
