- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

- name: Install Java
  become: yes
  yum:
    name: "java-1.8.0-openjdk"
    state: latest

- name: Add Confluent Dist Yum Repo
  become: yes
  yum_repository:
    name: Confluent.dist
    file: confluent
    description: "Confluent repository (dist)"
    baseurl: "{{confluent.repository.redhat.dist.baseurl}}"
    gpgcheck: "{{confluent.repository.redhat.dist.gpgcheck}}"
    gpgkey: "{{confluent.repository.redhat.dist.gpgkey}}"
    enabled: "{{confluent.repository.redhat.dist.enabled}}"
  notify: yum-clean-all

- name: Add Confluent Yum Repo
  become: yes
  yum_repository:
    name: Confluent
    file: confluent
    description: "Confluent repository"
    baseurl: "{{confluent.repository.redhat.main.baseurl}}"
    gpgcheck: "{{confluent.repository.redhat.main.gpgcheck}}"
    gpgkey: "{{confluent.repository.redhat.main.gpgkey}}"
    enabled: "{{confluent.repository.redhat.main.enabled}}"
  notify: yum-clean-all

- meta: flush_handlers

- name: Install the Confluent Platform
  become: yes
  yum:
    name: "{{confluent.package_name}}"
    state: latest
