- name: broker group
  become: yes
  group:
    name: "{{kafka.broker.group}}"

- name: broker user
  become: yes
  user:
    name: "{{kafka.broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka.broker.group}}"

- name: create broker data directories
  become: yes
  file:
    path: "{{item}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0755
  with_items: "{{kafka.broker.datadir}}"

- name: broker ssl config
  become: yes
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"

- name: create systemd override file
  become: yes
  file:
    path: "{{kafka.broker.systemd_override}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0640

- name: write environment variables
  become: yes
  template:
    src: environment.j2
    dest: "{{kafka.broker.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  notify:
    - reload systemd

- name: broker configure service
  become: yes
  systemd:
    name: "{{kafka.broker.service_name}}"
    enabled: "{{kafka.broker.systemd.enabled}}"
    state: "{{kafka.broker.systemd.state}}"
