- name: install epel-release
  become: yes
  command: amazon-linux-extras install epel -y

- name: install epel-release
  become: yes
  command: amazon-linux-extras install ansible2 -y

- name: prepare topic-create script
  become: yes
  template:
    src: topic_create.yml.j2
    dest: /home/ec2-user/topic_create.yml
    owner: ec2-user
    group: ec2-user
    mode: 0700
